### ISSUE TITLE
missing module suds

### ISSUE THREAD

**Issue by sposs** [DIRACGrid/Externals#1]
To run the VOMSService code, the python module suds needs to be installed by hand.
```python
>>> from DIRAC.Core.Security.VOMSService import VOMSService
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "DIRAC/Core/Security/VOMSService.py", line 5, in <module>
    from DIRAC.Core.Utilities.SOAPFactory import getSOAPClient
  File "DIRAC/Core/Utilities/SOAPFactory.py", line 4, in <module>
    import suds
ImportError: No module named suds
```
Would be nice if it could be included.

**Comment by fstagni** [comment]
Done
