### ISSUE TITLE
OpenSSl version of v6r5p4 breaks on CentOS7

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/Externals#26]
[chaen@localhost dirac]$ ./dirac-install -r v8r5p3 -l LHCb -e LHCb -t server
[...]
[chaen@localhost dirac]$ lhcb-proxy-init
Generating proxy...
Enter Certificate password:
Added VOMS attribute /lhcb/Role=user
Uploading proxy for lhcb_user...
Uploading proxy for private_pilot...
Traceback (most recent call last):
  File "/home/chaen/dirac/DIRAC/FrameworkSystem/scripts/dirac-proxy-init.py", line 273, in <module>
    pI.printInfo()
  File "/home/chaen/dirac/DIRAC/FrameworkSystem/scripts/dirac-proxy-init.py", line 178, in printInfo
    resultProxyInfoAsAString = ProxyInfo.getProxyInfoAsString( self.__proxyGenerated )
  File "/home/chaen/dirac/DIRAC/Core/Security/ProxyInfo.py", line 78, in getProxyInfoAsString
    retVal = getProxyInfo( proxyLoc, disableVOMS )
  File "/home/chaen/dirac/DIRAC/Core/Security/ProxyInfo.py", line 66, in getProxyInfo
    retVal = VOMS().getVOMSAttributes( chain )
  File "/home/chaen/dirac/DIRAC/Core/Security/VOMS.py", line 32, in getVOMSAttributes
    result = self.getVOMSProxyInfo( proxy, "all" )
  File "/home/chaen/dirac/DIRAC/Core/Security/VOMS.py", line 119, in getVOMSProxyInfo
    res = proxyDict[ 'chain' ].getVOMSData()
  File "/home/chaen/dirac/DIRAC/Core/Security/X509Chain.py", line 356, in getVOMSData
    res = cert.getVOMSData()
  File "/home/chaen/dirac/DIRAC/Core/Security/X509Certificate.py", line 197, in getVOMSData
    attr = GSI.crypto.asn1_loads( str(extBundle[1]) ).get_value()
GSI.crypto.Error: [('asn1 encoding routines', 'ASN1_get_object', 'too long')]

Using v6r5 works perfectly

**Comment by atsareg** [comment]
v6r5 uses openssl 1.0.2h whereas  v6r5p4 is downgraded to 1.0.1g because of the RAL Castor. Is this Castor problem is still in the way ?

**Comment by chaen** [comment]
In principle it should not, but it must be tested

**Comment by fstagni** [comment]
We'll see again after https://github.com/DIRACGrid/Externals/pull/27
